version: "1"
services:
  question:
    image: soymun/site:latest
    depends_on:
      - postgres_db
      - rabbitmq
    networks:
      - network
    expose:
      - 8880
    environment:
      - SPRING_DATASOURCE_URL=jdbc:postgresql://postgres_db:5432/postgres
      - SPRING_DATASOURCE_USERNAME=postgres
      - SPRING_DATASOURCE_PASSWORD=qwerty
      - MINIO_ENDPOINT=http://minio:9000
    ports:
      - "8880:8880"
    restart: unless-stopped

  sql:
    image: soymun/execute-sql:latest
    depends_on:
      - postgres_db
      - rabbitmq
      - question
    networks:
      - network
    expose:
      - 8882
    environment:
      - SPRING_DATASOURCE_URL=jdbc:postgresql://postgres_db:5432/postgres
      - SPRING_DATASOURCE_USERNAME=postgres
      - SPRING_DATASOURCE_PASSWORD=qwerty
    ports:
      - "8882:8882"
    restart: unless-stopped

  java-execute:
    image: soymun/java-execute:latest
    depends_on:
      - question
    networks:
      - network
    expose:
      - 8883
    ports:
      - "8883:8883"
    restart: unless-stopped

  minio:
    container_name: minio
    image: minio/minio:latest
    volumes:
      - "/minio:/data"
    ports:
      - "9000:9000"
      - "37207:37207"
    networks:
      - network
    restart: unless-stopped
    environment:
      MINIO_ROOT_USER: "usercoffeemachine"
      MINIO_ROOT_PASSWORD: "usercoffeemachine"
    command: server /data
    healthcheck:
      test: [ "CMD", "curl", "-f", "http://localhost:9000/minio/health/live" ]
      interval: 30s
      timeout: 20s
      retries: 3

  rabbitmq:
    image: rabbitmq:3.10.7-management
    hostname: rabbitmq
    restart: unless-stopped
    volumes:
      - ./rabbitmq:/var/lib/rabbitmq
    networks:
      - network
    ports:
      - 15672:15672
      - 5672:5672

  postgres_db:
    image: postgres:11.8
    environment:
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=qwerty
    networks:
      - network
    expose:
      - 5432
    ports:
      - "5432:5432"
    volumes:
      - ./postgres_data:/var/lib/postgresql/data

networks:
  network: