version: "1"
services:
  question:
    image: soymun/site:1.0.4
    depends_on:
      - postgres_db
      - rabbitmq
    networks:
      - network
    expose:
      - 8880
    environment:
      - SPRING_DATASOURCE_URL=jdbc:postgresql://postgres_db:5432/postgres
      - SPRING_DATASOURCE_USERNAME=postgres
      - SPRING_DATASOURCE_PASSWORD=qwerty
      - MINIO_ENDPOINT=http://minio:9000
      - SPRING_RABBITMQ_HOST=rabbitmq
    ports:
      - "8880:8880"
    restart: unless-stopped

  sql:
    image: soymun/execute-sql:1.0.4
    depends_on:
      - postgres_db
      - rabbitmq
      - question
    networks:
      - network
    expose:
      - 8882
    environment:
      - SPRING_DATASOURCE_URL=jdbc:postgresql://postgres_db:5432/postgres
      - SPRING_DATASOURCE_USERNAME=postgres
      - SPRING_DATASOURCE_PASSWORD=qwerty
    ports:
      - "8882:8882"
    restart: unless-stopped

  sql-mysql:
    image: soymun/execute-sql:1.0.4
    depends_on:
      - mysql_db
      - rabbitmq
      - question
    networks:
      - network
    expose:
      - 8884
    environment:
      - SPRING_DATASOURCE_URL=jdbc:mysql://mysql_db:3306/stage
      - SPRING_DATASOURCE_USERNAME=root
      - SPRING_DATASOURCE_PASSWORD=secret
      - SPRING_JPA_DATABASE-PLATFORM=org.hibernate.dialect.MySQLDialect
      - SQL_QUEUE_CHECK=mysql-check
      - SQL_QUEUE_SCHEMA=mysql-schema
      - SQL_QUEUE_EXECUTE=mysql-execute
    ports:
      - "8884:8882"
    restart: unless-stopped

  mysql_db:
    image: mysql:9.1.0
    restart: unless-stopped
    ports:
      - "3306:3306"
    environment:
      MYSQL_ROOT_PASSWORD: secret
      MYSQL_DATABASE: stage
      MYSQL_USER: example
      MYSQL_PASSWORD: secret2
    volumes:
      - ./dbdata:/var/lib/mysql/

  java-execute:
    image: soymun/java-execute:1.0.4
    depends_on:
      - question
    networks:
      - network
    expose:
      - 8883
    ports:
      - "8883:8883"
    restart: unless-stopped

  minio:
    container_name: minio
    image: minio/minio:latest
    volumes:
      - ./minio:/data
    ports:
      - "9000:9000"
      - "37207:37207"
    networks:
      - network
    restart: unless-stopped
    environment:
      MINIO_ROOT_USER: "usercoffeemachine"
      MINIO_ROOT_PASSWORD: "usercoffeemachine"
    command: server /data
    healthcheck:
      test: [ "CMD", "curl", "-f", "http://localhost:9000/minio/health/live" ]
      interval: 30s
      timeout: 20s
      retries: 3

  rabbitmq:
    image: rabbitmq:3.10.7-management
    hostname: rabbitmq
    restart: unless-stopped
    volumes:
      - ./rabbitmq:/var/lib/rabbitmq
    networks:
      - network
    ports:
      - 15672:15672
      - 5672:5672

  postgres_db:
    image: postgres:11.8
    environment:
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=qwerty
    networks:
      - network
    expose:
      - 5432
    ports:
      - "5432:5432"
    volumes:
      - ./postgres_data:/var/lib/postgresql/data

  python-execute:
    image: soymun/python-execute
    networks:
      - network
    depends_on:
      - rabbitmq
    restart: unless-stopped

networks:
  network: