spring:
  datasource:
    username: postgres
    password: qwerty
    url: jdbc:postgresql://localhost:5432/postgres
  mail:
    host: smtp.yandex.ru
    port: 465
    username: шо ты тут ищешь?
    password:
    properties:
      mail:
        smtp:
          connectiontimeout: 10000
          timeout: 10000
          writetimeout: 10000
          socketFactory:
            fallback: true
    ssl:
      enabled: true
  application:
    name: notification

minio:
  login: usercoffeemachine
  password: usercoffeemachine
  endpoint: http://localhost:9000