eureka:
  instance:
    preferIpAddress: true
  client:
    registerWithEureka: true
    fetchRegistry: true
    serviceUrl:
      defaultZone: http://eurika:8070/eureka/

server:
  port: 80

spring:
  cloud:
    loadbalancer.ribbon.enabled: false
    gateway:
      routes:
        - id: site
          uri: lb://site
          predicates:
            - Path=/site/**
          filters:
            - RewritePath=/site/(?<path>.*), /$\{path}
        - id: file
          uri: lb://file
          predicates:
            - Path=/file/**
          filters:
            - RewritePath=/file/(?<path>.*), /$\{path}

management:
  endpoints:
    web:
      exposure:
        include: "*"