server:
  port: 8882
spring:
  jpa:
    database-platform: org.hibernate.dialect.PostgreSQLDialect
  datasource:
    url: jdbc:postgresql://localhost:5432/postgres
    username: postgres
    password: qwerty
  rabbitmq:
    template:
      exchange: courses
    host: rabbitmq
