server:
  port: 8882
spring:
  jpa:
    database-platform: org.hibernate.dialect.PostgreSQLDialect
  datasource:
    url: jdbc:postgresql://localhost:5432/postgres
    username: postgres
    password: qwerty
    hikari:
      maximum-pool-size: 25
      minimum-idle: 10000
  rabbitmq:
    template:
      exchange: courses
    host: localhost

sql:
  queue:
    check: postgresql-check
    schema: postgresql-schema
    execute: postgresql-execute
