server:
  port: 8080
spring:
  jpa:
    hibernate:
      ddl-auto: none
    open-in-view: false
  datasource:
    username: postgres
    password: qwerty
    url: jdbc:postgresql://localhost:5432/courses
  liquibase:
    enabled: true
jwt:
  token:
    security: soymun
    validate: 3600000
