server:
  port: 8880
  servlet:
    context-path: /site
spring:
  application:
    name: site
  eureka:
    instance:
      preferIpAddress: true
    client:
      registerWithEureka: true
      fetchRegistry: true
      serviceUrl:
        defaultZone: http://eurika:8070/eureka/
  jpa:
    hibernate:
      ddl-auto: none
    open-in-view: false
    database-platform: org.hibernate.dialect.PostgreSQLDialect
  datasource:
    username: postgres
    password: qwerty
    url: jdbc:postgresql://localhost:5432/postgres
  liquibase:
    enabled: true
  rabbitmq:
    host: rabbitmq
jwt:
  token:
    security: soymun
    validate: 3600000