server:
  port: 8880
  servlet:
    context-path: /api
spring:
  application:
    name: site
  jpa:
    hibernate:
      ddl-auto: none
    open-in-view: false
    database-platform: org.hibernate.dialect.PostgreSQLDialect
  datasource:
    username: postgres
    password: qwerty
    url: jdbc:postgresql://localhost:5432/postgres
  liquibase:
    enabled: true
  rabbitmq:
    host: localhost
  servlet:
    multipart:
      max-file-size: 100MB

minio:
  login: usercoffeemachine
  password: usercoffeemachine
  endpoint: http://localhost:9000
jwt:
  token:
    security: 1932485710938450193450SKJDHTO3UI2H456KJ3ND8EGU7YOI213J4N51058U4HJDSNFH9183Y45UT1U345
    validate: 3600000
    refresh: 999999999