name: Docker Image CI

on:
  push:
    branches: [ "master" ]
    tags:
      - '*'

env:
  username: ${{ secrets.DOCKERHUB_USERNAME }}
  password: ${{ secrets.DOCKERHUB_TOKEN }}

jobs:
  docker:
    runs-on: ubuntu-latest
    steps:
      -
        name: Checkout
        uses: actions/checkout@v4
      -
        name: Set up QEMU
        uses: docker/setup-qemu-action@v3
      -
        name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v3
      -
        name: Login to Docker Hub
        uses: docker/login-action@v3
        with:
          username: ${{ env.username }}
          password: ${{ env.password }}

      - name: Build and push execute sql
        uses: docker/build-push-action@v6
        with:
          context: ./execute-sql/
          push: true
          tags: execute-sql:latest

      - name: Build and push java execute
        uses: docker/build-push-action@v6
        with:
          context: ./java-execute/
          push: true
          tags: java-execute:latest

      - name: Build and push site
        uses: docker/build-push-action@v6
        with:
          context: ./site/
          push: true
          tags: site:latest