name: Docker Image CI

on:
  push:
    tags:
      - '*'

jobs:
  docker:
    runs-on: ubuntu-latest
    steps:
      -
        name: Checkout
        uses: actions/checkout@v4
      -
        name: Set up QEMU
        uses: docker/setup-qemu-action@v3
      -
        name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v3
      -
        name: Login to Docker Hub
        uses: docker/login-action@v3
        with:
          username: ${{secrets.DOCKER_USERNAME}}
          password: ${{secrets.DOCKERHUB_TOKEN}}

      - name: Build and push execute sql
        uses: docker/build-push-action@v6
        with:
          context: ./execute-sql/
          push: true
          tags: soymun/execute-sql:{{$CI_COMMIT_TAG}}

      - name: Build and push java execute
        uses: docker/build-push-action@v6
        with:
          context: ./java-execute/
          push: true
          tags: soymun/java-execute:{{$CI_COMMIT_TAG}}

      - name: Build and push site
        uses: docker/build-push-action@v6
        with:
          context: ./site/
          push: true
          tags: soymun/site:{{$CI_COMMIT_TAG}}